[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
number_guessing_game = "H2QtoCz4CcjVZsHrFxzngLJ8z4rQatMnAspT9w3q12LE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
